namespace: "inexio"
name: "thola"
version: "1.0.3"
readme: "README.md"
authors:
  - "Thola team [team@thola.io]"
license_file: "LICENSE"
homepage: "https://thola.io"
tags:
  - collection
repository: "https://github.com/inexio/thola-ansible"
description: "Integrates the functionalities of Thola into Ansible"
build_ignore:
  - "*.tar.gz"
